#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NaaStockScanner.Droid.Resource", IsApplication=true)]

namespace NaaStockScanner.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::NaaStockScanner.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::NaaStockScanner.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::NaaStockScanner.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::NaaStockScanner.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::NaaStockScanner.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::NaaStockScanner.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::NaaStockScanner.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::NaaStockScanner.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::NaaStockScanner.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::NaaStockScanner.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::NaaStockScanner.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::NaaStockScanner.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::NaaStockScanner.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::NaaStockScanner.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::NaaStockScanner.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::NaaStockScanner.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::NaaStockScanner.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::NaaStockScanner.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::NaaStockScanner.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::NaaStockScanner.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::NaaStockScanner.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::NaaStockScanner.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::NaaStockScanner.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::NaaStockScanner.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::NaaStockScanner.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::NaaStockScanner.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::NaaStockScanner.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::NaaStockScanner.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::NaaStockScanner.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::NaaStockScanner.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::NaaStockScanner.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::NaaStockScanner.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::NaaStockScanner.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::NaaStockScanner.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::NaaStockScanner.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::NaaStockScanner.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::NaaStockScanner.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::NaaStockScanner.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::NaaStockScanner.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::NaaStockScanner.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::NaaStockScanner.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::NaaStockScanner.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::NaaStockScanner.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::NaaStockScanner.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::NaaStockScanner.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::NaaStockScanner.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::PCLStorage.Resource.String.ApplicationName = global::NaaStockScanner.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::NaaStockScanner.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::NaaStockScanner.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::NaaStockScanner.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarColor = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int ahBarLength = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int ahBarWidth = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public const int ahCircleColor = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int ahDelayMillis = 2130771982;
			
			// aapt resource value: 0x7f010010
			public const int ahRadius = 2130771984;
			
			// aapt resource value: 0x7f01000b
			public const int ahRimColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int ahRimWidth = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int ahSpinSpeed = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int ahText = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int ahTextColor = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int ahTextSize = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backspace = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_errorstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_successstatus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundedbg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roundedbgdark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050020
			public const int MyButton = 2131034144;
			
			// aapt resource value: 0x7f05001a
			public const int button1 = 2131034138;
			
			// aapt resource value: 0x7f050013
			public const int button10 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int button11 = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int button12 = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int button13 = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int button2 = 2131034139;
			
			// aapt resource value: 0x7f05000a
			public const int button3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int button4 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int button5 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int button6 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int button7 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int button8 = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int button9 = 2131034130;
			
			// aapt resource value: 0x7f050021
			public const int editText1 = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int frameLayout1 = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int frameLayout2 = 2131034146;
			
			// aapt resource value: 0x7f050019
			public const int linearLayout1 = 2131034137;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout2 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout3 = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayout4 = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout5 = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout6 = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout7 = 2131034115;
			
			// aapt resource value: 0x7f05001e
			public const int loadingImage = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int loadingProgressBar = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int loadingProgressWheel = 2131034143;
			
			// aapt resource value: 0x7f050017
			public const int space1 = 2131034135;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int textView2 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textView3 = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int textView4 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int textView5 = 2131034117;
			
			// aapt resource value: 0x7f050024
			public const int textViewConfirm = 2131034148;
			
			// aapt resource value: 0x7f05001d
			public const int textViewStatus = 2131034141;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CaptureStockQuantityView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FirstView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loading = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingimage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loadingprogress = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ReadyToScanView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ScanConfirmationView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SplashScreen = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] ProgressWheel = new int[] {
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
